name: discoprocess
channels:
  - conda-forge
dependencies:
  - matplotlib
  - seaborn
  - numpy
  - pandas>=1.4.2
  - pytest
  - pytest-mock
  - pytest-cov
  - openpyxl
  - scikit-learn # sklearn

# +SciencePlots (via pip install)